### ISSUE TITLE
16GB VRAM Usage

### ISSUE THREAD

**Issue by markhill343** [tin2tin/Pallaidium#119]
Hi!

first i wanted to thank you for the project!

I have 16GB VRAM available. 
While running Image2Video the VRAM usage never exeeds ~8gb 

Settings i used:
![grafik](https://github.com/user-attachments/assets/2e821e3e-81f8-4340-8c0d-3d0b22fb4807)

Nvidia-smi
![grafik](https://github.com/user-attachments/assets/ecdac542-7b30-4d52-9d03-14d392cecd13)

Vram usage:
![Screenshot 2024-09-21 154317](https://github.com/user-attachments/assets/c8b79eda-f5a2-463d-89bc-1af42cde9a1b)

Code Extract:
![grafik](https://github.com/user-attachments/assets/a405033e-4544-43d1-a82b-1dbb92270a7f)
The result from the low vram calc results in 15.99 which is of course smaller than 16. Is this expected behaviour? 
Can this be altered or would it result in a overflow of VRAM and a crash?

**Comment by tin2tin** [comment]
Hi @markhill343

You could change the limit value to lower that line (save the script, F3 > reload scripts), and see how long it'll take. (If you're not familiar with dev in Blender, here are some hints for fast tweaking of a script: https://github.com/tin2tin/Pallaidium/issues/105#issuecomment-2320701681 )

These are the optimize functions: https://github.com/tin2tin/Pallaidium/blob/64cfd67e7dab75b486851a384abd1e930e30a852/__init__.py#L2199

The challenging part is staying below overshooting the VRAM because offloading into the Static Memory will slow things. AFAIR is the "hi" vram code demanding around 18 GB VRAM. And going directly to CUDA it's around 35-36 GB of VRAM. For me with 24 GB VRAM it's faster render to stay below 18 GB than 35 GB. 

Let me know how it goes. Are you on Windows?

**Comment by markhill343** [comment]
yes i am on windows. 

You are absolutly right!

"low_vram" settings with about 8gb: ~15s/it
Then i just changed the "low_vram" limit from a 16 into a 15 in the init.py and did 2 runs.

The first time it seemed to not overspil into the ram: ~24s/it
The second time it did resulting in a really bad time: ~67s/it
